service: ezstore 

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64  # Faster & cheaper!
  stage: dev
  region: eu-west-1
  profile: serverless-personal
  memorySize: 256

  deploymentBucket:
    name: "xd-serverless-deployments"

  versionFunctions: false

  environment:
    TABLE_NAME: !Ref dynamoDataStore
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt dynamoDataStore.Arn

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
    nativeZip: true
    treeShaking: true

package:
  individually: true

functions:
  ezstore_ingest:
    description: Quickly ingest and store data from test devices
    handler: src/functions/ingest.handle
    architecture: arm64
    events:
      - httpApi: 'POST /ezstore/v1/metrics/{deviceId}'

  ezstore_api:
    description: Expose data from devices in a simple REST API
    handler: src/functions/api.handle
    architecture: arm64
    events:
      - httpApi: 'GET /ezstore/v1/metrics/{deviceId}'

resources:
  Resources:
    dynamoDataStore:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ezstore
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: S
          - AttributeName: "sk"
            AttributeType: S
        KeySchema:
          - AttributeName: "pk"
            KeyType: HASH
          - AttributeName: "sk"
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
